name=UARDECS_PICO Library
version=1.0.3
author=H.kurosaki,K.yasuba
maintainer=uecs.org <kurosaki@uecs.jp>
sentence=A library that provides communication functions conforming to UECS, a common standard for horticulture in Japan.
paragraph=This library provides UDP server and Web server functions conforming to the UECS standard, enabling the implementation of UECS on the Raspberry Pi Pico. It supports the Raspberry Pi Pico and compatible boards based on the RP2040 or RP2350. The most ideal boards are the W5500-EVB-Pico and W5500-EVB-Pico2, which integrate the required W5500 Ethernet controller. The Ethernet library needed for W5500 is bundled, so no separate installation is required. See LICENSE.md for its license.
category=Communication
url=https://github.com/H-Kurosaki/UARDECS_PICO
architectures=rp2040,mbed_rp2040
